apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: health-platform
data:
  APP_ENV: "dev"
  APP_DEBUG: "1"
  TIMEZONE: "Europe/Paris"
  # DSNs
  MESSENGER_TRANSPORT_DSN: "amqp://rabbitmq:5672"
  MONGODB_URI: "mongodb://admin:adminpass@mongodb:27017"
