doctrine_mongodb:
  auto_generate_proxy_classes: true
  connections:
    default:
      server: '%env(MONGODB_URI)%'
  default_database: diabetes
  document_managers:
    default:
      auto_mapping: true
